version: "1"
services:
  - type: web
    name: Tech-20
    runtime: docker
    plan: free
    region: virginia
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit

    envVars:
      - key: SESSION_ID
        sync: false
      - key: TIMEZONE
        sync: false
      - key: PREFIX
        sync: false
      - key: POSTGRES_URL
        sync: false
